import urllib.request
import json
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from google import genai
from google.genai import types

# Config
SUPABASE_URL = "https://jicrumwdnwmjkotkbjtg.supabase.co"
SUPABASE_KEY = "sb_publishable_qKmdOmdtIZYB6i_pQEkt_Q_A7bp127D"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
LOCAL_COMPRESSED_DIR = "/Volumes/DADAfiles/TOMFOX/Compressed"
MAX_WORKERS = 3  # Safe multithreading
import shutil
import uuid

TARGET_TRACKS = [
    " Pocket Book (Vintage).mp3",
    " Pocket Book and Ink.mp3",
    "épanouissement.aif",
    "Açai Bowl.wav",
    "A Very Old Me.wav",
    "Some Cloud.wav"
]

client = genai.Client(api_key=GEMINI_API_KEY)

def log_progress(message):
    print(message)
    with open("tagging_progress.log", "a") as f:
        f.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {message}\n")

def get_all_tracks():
    tracks = []
    page = 0
    size = 1000
    while True:
        req = urllib.request.Request(
            f"{SUPABASE_URL}/rest/v1/tracks?select=id,file_name,folder,description,genre,subgenre,moods,instruments,textures,scenarios,human_tags&limit={size}&offset={page*size}", 
            headers={"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}"}
        )
        with urllib.request.urlopen(req) as res:
            chunk = json.loads(res.read())
            if not chunk:
                break
            # Filter specifically for the 6 target tracks
            filtered = [t for t in chunk if t['file_name'] in TARGET_TRACKS]
            tracks.extend(filtered)
            page += 1
    return tracks

def merge_arrays(old_list, new_list):
    if old_list is None: old_list = []
    if isinstance(old_list, str): old_list = [old_list]
    if new_list is None: new_list = []
    if isinstance(new_list, str): new_list = [new_list]
    # Combine and remove duplicates
    return list(set(old_list + new_list))

def update_track_tags(track_id, old_track, tags_json):
    # Retrieve and parse old subgenre which might be a JSON string
    old_subgenre = old_track.get("subgenre")
    if old_subgenre and isinstance(old_subgenre, str):
        try:
            old_subgenre = json.loads(old_subgenre)
        except:
            old_subgenre = [old_subgenre]
            
    # MERGE LOGIC: Keep old tags, add new tags, remove duplicates
    data = {
        "p_track_id": track_id,
        "p_subgenre": json.dumps(merge_arrays(old_subgenre, tags_json.get("subgenre"))),
        "p_moods": merge_arrays(old_track.get("moods"), tags_json.get("moods")),
        "p_instruments": merge_arrays(old_track.get("instruments"), tags_json.get("instruments")),
        "p_textures": merge_arrays(old_track.get("textures"), tags_json.get("textures")),
        "p_scenarios": merge_arrays(old_track.get("scenarios"), tags_json.get("scenarios")),
        "p_human_tags": merge_arrays(old_track.get("human_tags"), tags_json.get("human_tags")),
        "p_genre": tags_json.get("genre", old_track.get("genre", "")),
        "p_description": tags_json.get("description", old_track.get("description", ""))
    }
    
    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/rpc/update_track_tags_rpc", 
        data=json.dumps(data).encode('utf-8'),
        headers={"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}", "Content-Type": "application/json"},
        method='POST'
    )
    with urllib.request.urlopen(req) as res:
        pass

def process_track(track):
    track_id = track['id']
    folder = track.get('folder', '')
    file_name = track['file_name']
    
    if not folder:
        return f"Skipped {file_name} (No folder)"
        
    # FALLBACK/RESUME LOGIC: If a track already has a description generated by Gemini, skip it.
    # This ensures if internet drops, restarting the script will pick up EXACTLY where it left off.
    if track.get('description') and track.get('description').strip() != "":
        return f"Already tagged (Skipping): {file_name}"
    
    base_name = os.path.splitext(file_name)[0]
    mp3_name = f"{base_name}.mp3"
    mp3_path = os.path.join(LOCAL_COMPRESSED_DIR, folder, mp3_name)
    
    if not os.path.exists(mp3_path):
        return f"Skipped {file_name} (MP3 not found)"
        
    safe_temp_path = f"/tmp/safe_{uuid.uuid4().hex}.mp3"
    try:
        shutil.copy2(mp3_path, safe_temp_path)
        audio_file = client.files.upload(file=safe_temp_path)
        while audio_file.state.name == "PROCESSING":
            time.sleep(2)
            audio_file = client.files.get(name=audio_file.name)
            
        if audio_file.state.name == "FAILED":
            os.remove(safe_temp_path)
            return f"Failed {file_name} (Gemini processing error)"
            
        prompt = """
        You are an expert music supervisor and audio tagger. Actively listen to the provided audio track.
        Provide an extremely precise, highly specific, and non-redundant set of tags. 
        WE NEED A HUGE AMOUNT OF METADATA. Be exhaustive. Generate as many accurate tags as possible for each category.
        
        CRITICAL RULE FOR DIVERSITY: 
        When generating `scenarios` and `human_tags`, cast a wide net. Ensure the scenarios cover completely different and disparate contexts that still accurately fit the music. 
        For example, if a track is light and bouncy, do not just list 10 variations of "corporate presentation". Include "children's educational video", "cooking tutorial", "morning vlog", "indie puzzle game", etc. 
        Give it diverse use-cases so it appears in many different user searches!
        
        Return a strict JSON object with this exact schema:
        - genre: (string) The main overarching genre.
        - subgenre: (array of strings) Generate AT LEAST 5 to 8 highly specific subgenres.
        - moods: (array of strings) Generate AT LEAST 10 to 15 exact emotional states and feelings.
        - instruments: (array of strings) Generate AT LEAST 8 to 12 prominent instruments and how they are played.
        - textures: (array of strings) Generate AT LEAST 8 to 12 sonic qualities (e.g. ethereal, gritty, warm).
        - scenarios: (array of strings) Generate AT LEAST 8 to 12 highly specific, DIAMETRICALLY DIVERSE use-case scenarios. 
        - energy_level: (string) "Low", "Medium", or "High".
        - human_tags: (array of strings) Generate AT LEAST 15 to 20 other relevant comma-separated tags (tempo feelings, era, specific styles, cultural vibes).
        - description: (string) A rich, evocative 2-3 sentence narrative description.
        
        Respond ONLY with valid JSON.
        """
        
        tags = None
        for attempt in range(3):
            try:
                response = client.models.generate_content(
                    model='gemini-2.5-flash-lite',
                    contents=[audio_file, prompt],
                    config=types.GenerateContentConfig(response_mime_type="application/json")
                )
                tags = json.loads(response.text)
                break
            except Exception as e:
                log_progress(f"Attempt {attempt+1} failed for {file_name}: {str(e)}")
                time.sleep(2)
                
        if not tags:
            raise Exception("Failed to generate valid JSON after 3 attempts")
        
        # IMMEDIATELY UPDATE DATABASE (Includes merging with old tags)
        update_track_tags(track_id, track, tags)
        
        # Cleanup file from Gemini servers
        client.files.delete(name=audio_file.name)
        os.remove(safe_temp_path)
        
        msg = f"Success: {file_name} successfully tagged & saved to DB."
        log_progress(msg)
        return msg
        
    except Exception as e:
        msg = f"Error on {file_name}: {str(e)}"
        log_progress(msg)
        return msg

def main():
    log_progress("=== STARTING BATCH TAGGING PROCESS ===")
    tracks = get_all_tracks()
    log_progress(f"Total tracks in database: {len(tracks)}")
    
    start_time = time.time()
    success_count = 0
    
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(process_track, t): t for t in tracks}
        
        for future in as_completed(futures):
            result = future.result()
            if result.startswith("Success"):
                success_count += 1
                
    elapsed = time.time() - start_time
    log_progress(f"=== FINISHED ===")
    log_progress(f"Processed {success_count} tracks in {elapsed:.2f} seconds.")

if __name__ == "__main__":
    main()
