UPDATE playlists SET cover_url = 'https://picsum.photos/seed/New%20Music/800/800' WHERE title = 'New Music';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Pop%20Culture%20Quirk/800/800' WHERE title = 'Pop Culture Quirk';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Arcade%20Overdrive/800/800' WHERE title = 'Arcade Overdrive';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Playful%20Curiosity/800/800' WHERE title = 'Playful Curiosity';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Serious%20Journalism/800/800' WHERE title = 'Serious Journalism';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Great%20For%3A%20Explainers/800/800' WHERE title = 'Great For: Explainers';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Signal%20Curiosity/800/800' WHERE title = 'Signal Curiosity';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Synth%3A%20Calm%2C%20Digital/800/800' WHERE title = 'Synth: Calm, Digital';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Staff%20Picks/800/800' WHERE title = 'Staff Picks';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Vox%20Borders%20Sessions%2C%20Vol.%204/800/800' WHERE title = 'Vox Borders Sessions, Vol. 4';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Historical%20Discovery/800/800' WHERE title = 'Historical Discovery';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Ethereal%20Dreamy/800/800' WHERE title = 'Ethereal Dreamy';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Radiant%20Synths/800/800' WHERE title = 'Radiant Synths';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Closing%20Remarks/800/800' WHERE title = 'Closing Remarks';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Epic%20Synth/800/800' WHERE title = 'Epic Synth';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Shadow%20Pulse/800/800' WHERE title = 'Shadow Pulse';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Exploring%20Space/800/800' WHERE title = 'Exploring Space';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Dark%20News/800/800' WHERE title = 'Dark News';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/High%20Stakes/800/800' WHERE title = 'High Stakes';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Drop%20The%20Beat/800/800' WHERE title = 'Drop The Beat';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Human%20Stories/800/800' WHERE title = 'Human Stories';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Light%20Explainer/800/800' WHERE title = 'Light Explainer';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Drum%20Solo%20Energy/800/800' WHERE title = 'Drum Solo Energy';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Shadow%20Jazz/800/800' WHERE title = 'Shadow Jazz';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Floating%20Uncertainty/800/800' WHERE title = 'Floating Uncertainty';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Curious%20Jazz/800/800' WHERE title = 'Curious Jazz';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Dark%20Atmosphere/800/800' WHERE title = 'Dark Atmosphere';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Tech%20Pulse/800/800' WHERE title = 'Tech Pulse';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Lo-Fi/800/800' WHERE title = 'Lo-Fi';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Solo%20Piano/800/800' WHERE title = 'Solo Piano';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Minimal%20Percussive%20Underscore/800/800' WHERE title = 'Minimal Percussive Underscore';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Slow%20Drum%20Solo/800/800' WHERE title = 'Slow Drum Solo';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Dark%20Arpeggio/800/800' WHERE title = 'Dark Arpeggio';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Code%20Breach/800/800' WHERE title = 'Code Breach';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Nostalgia/800/800' WHERE title = 'Nostalgia';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Cool%20Hip%20Hop/800/800' WHERE title = 'Cool Hip Hop';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Film/800/800' WHERE title = 'Film';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Space/800/800' WHERE title = 'Space';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Dark%20Explainer/800/800' WHERE title = 'Dark Explainer';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Classical%20Hybrid/800/800' WHERE title = 'Classical Hybrid';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Dark%20Texture/800/800' WHERE title = 'Dark Texture';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Vox%20Borders%20Sessions%2C%20Vol.%203/800/800' WHERE title = 'Vox Borders Sessions, Vol. 3';
UPDATE playlists SET cover_url = 'https://picsum.photos/seed/Vox%20Borders%20Sessions%2C%20Vol.%202/800/800' WHERE title = 'Vox Borders Sessions, Vol. 2';
