UPDATE playlists SET cover_url = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" fill="%23aec6cf" /><image href="https://upload.wikimedia.org/wikipedia/commons/a/a2/Vox_logo.svg" x="20" y="35" width="60" height="30" /></svg>' WHERE title ILIKE '%Vox Borders Sessions%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-M4YEVFDUk8A?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Arcade Overdrive%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-4t95oguiv-s?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Playful Curiosity%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-LnAO9mxUh98?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Serious Journalism%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-Yga3Fvcsf5I?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Great for explainers%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-XWX4MUO4qCc?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Signal Curiosity%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-Tyw_6US02nU?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Synth Calm Digital%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-XLO_DVkqjsA?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Staff Picks%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-1478760327741-6cb31eda2283?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Ethereal dreamy%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-nfW4k2Dwp8A?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Radiant Synths%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-JrZ36KYaqP8?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Epic Synth%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-VJMTRCTnJxk?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Shadow pulse%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-c6J4Q0x8AAk?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Exploring space%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-W2VNNi9fhQc?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Dark news%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-gdz6RJ6hxLk?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%High stakes%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-1517230878791-4d28214057c2?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Drop the Beat%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-hxp5cuEDZEM?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Human stories%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-wFvlgfyhJRE?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Light Explainer%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-I4QiKgfvKFY?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Drum solo energy%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-NX4wLMC4RRA?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Shadow Jazz%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-4YJJnm4XH60?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Dark Atmosphere%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-nQluVjXmycc?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Tech pulse%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-s_7f2iJf8nc?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Lo fi%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-jFc549i-jpw?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Solo piano%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-2t8TMBHezY4?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Minimal percussive underscore%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-Meksp9wj3kg?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Slow drum solo%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-BabUQWicolM?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Code Breach%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-CQuNSE7iSz0?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Nostalgia%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Film%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-c7jiWulZLK0?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Space%';
UPDATE playlists SET cover_url = 'https://images.unsplash.com/photo-Yga3Fvcsf5I?auto=format&fit=crop&q=80&w=800' WHERE title ILIKE '%Dark explainer%';
